// Story Writing
const storyWritingSilverData = {
  name: "Story Writing For Kids",
  extraPrice: 10,
  extraLimit: 100,
  title: "Silver",
  services: ["7 Days Delivery", "5 Revision", "Up to 1000 Words (optional)"],
  price: 99,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "Words",
};

const storyWritingGoldData = {
  name: "Story Writing For Kids",
  extraPrice: 10,
  extraLimit: 100,
  title: "Gold",
  services: ["10 Days Delivery", "7 Revision", "Up to 2000 Words (optional)"],
  price: 149,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "Words",
};

const storyWritingPlatinumData = {
  name: "Story Writing For Kids",
  extraPrice: 10,
  extraLimit: 100,
  title: "Platinum",
  services: [
    "14 Days Delivery",
    "Unlimited Revisions",
    "Up to 5000 Words (optional)",
    "Outline",
    "Text Rewrite",
    "Topic Research",
  ],
  price: 349,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "Words",
};

// 2)Children’s book designing

const bookCoverPlatinumData = {
  name: "Children’s book designing",
  extraPrice: 10,
  extraLimit: 100,
  title: "Platinum",
  services: [
    "Front & Back cover",
    "7 Days Delivery",
    "7 Revisions",
    "Formatting for Amazon",
    "Back & Spine Designs",
    "Jacket Cover",
    "Original Design",
    "Commercial use",
    "Copy right",
    "Source File",
    "Different 3D Mockup",
    "JPG, PNG PLUS Custom File",
  ],
  price: 99,
  totalPrice: 0,
  extra: 0,
  options: false,
  extraType: "",
};

const bookCoverSilverData = {
  name: "Children’s book designing",
  extraPrice: 10,
  extraLimit: 100,
  title: "Silver",
  services: [
    "Front cover",
    "5 Days Delivery",
    "3 Revisions",
    "Jacket Cover",
    "Original Design",
    "Source File",
    "3D Mockup",
    "JPG, PNG",
  ],
  price: 49,
  totalPrice: 0,
  extra: 0,
  options: false,
  extraType: "",
};

const bookCoverGoldData = {
  name: "Children’s book designing",
  extraPrice: 0,
  extraLimit: 0,
  title: "Gold",
  services: [
    "Front & Back cover",
    "6 Days Delivery",
    "5 Revisions",
    "Back & Spine Designs",
    "Jacket Cover",
    "Original Design",
    "Source File",
    "3D Mockup",
    "JPG, PNG",
  ],
  price: 69,
  totalPrice: 0,
  extra: 0,
  options: false,
  extraType: "",
};

const bookInteriorColoringData = {
  name: "Children’s book designing",
  extraPrice: 30,
  extraLimit: 1,
  title: "Coloring Book",
  services: [
    "Up to 25 pages(optional)",
    "25 Days Delivery",
    "5 Revisions",
    "Front and back cover",
    "Coloring pages",
    "High Resolution",
    "Background/Scene",
    "Multiple Character",
    "Custom Files",
    "Print ready pdf file JPG PNG",
    "Copy right Original",
  ],
  price: 749,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const bookInteriorEbookData = {
  name: "Children’s book designing",
  extraPrice: 30,
  extraLimit: 1,
  title: "EBook",
  services: [
    "Up to 15 pages or 8 Spread (optional)",
    "40 Days Delivery",
    "5 Revisions",
    "Front and back cover (optional)",
    "Coloring pages",
    "High Resolution",
    "Background/Scene",
    "Multiple Character",
    "Custom Files",
    "Source File",
    "Print ready pdf file JPG PNG",
    "Copy right Original",
  ],
  price: 749,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const bookInteriorPaperbackgData = {
  name: "Children’s book designing",
  extraPrice: 30,
  extraLimit: 1,
  title: "Paper Back",
  services: [
    "Up to 40 pages or 20 Spread (optional)",
    "59 Days Delivery",
    "5 Revisions",
    "Front and back cover",
    "Formatting for Amazon (optional)",
    "Fast Delivery (Optional)",
    "Original Illustrations",
    "Coloring pages",
    "High Resolution",
    "Background/Scene",
    "Multiple Character",
    "Custom Files",
    "15-days support",
    "Print ready pdf file JPG PNG",
    "Copy right Original",
  ],
  price: 1999,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const bookFullandFlaggerData = {
  name: "Children’s book designing",
  extraPrice: 30,
  extraLimit: 1,
  title: "Full and Flagger",
  services: [
    "60 Days Delivery",
    "Unlimited Revisions",
    "Up to 40 pages or 20 Spread (optional)",
    "Story writing",
    "Up to words 2500 (optional)",
    "Number of pages 40 (optional)",
    "A+ Content ",
    "Book Uploading",
    "1 Niche",
    "3 Categories",
    "50 Keyword",
    "Competitive Analysis",
    "1 Title SEO",
    "SEO Optimized listing Description ",
    "Launch Strategy",
    "Promotional Campaign",
    "Front and back cover",
    "Formatting for Amazon (optional)",
    "Fast Delivery (Optional)",
    "Original Illustrations",
    "Coloring pages",
    "High Resolution",
    "Background/Scene",
    "Multiple Character",
    "Custom Files",
    "15-days support",
    "Print ready pdf file JPG PNG",
    "Copy right Original",
  ],
  price: 3999,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

// 3)Book Layout Design

const bookLayoutSilverData = {
  name: "Book Layout Design",
  extraPrice: 1,
  extraLimit: 1,
  title: "Silver",
  services: [
    "5 Days Delivery",
    "5 Revisions",
    "Up to 200 Interior pages(optional)",
    "Images",
    "Cover Formating",
    "All trim size options",
    "Paperback, eBook & Hardcover",
    "Source File",
    "Print Ready PDF",
    "EBook Files (EPUB, MOBI, DOCX)",
    "Help In Approving from KDP",
    "Clickable Table of Contents (TOC)",
  ],
  price: 199,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const bookLayoutGoldData = {
  name: "Book Layout Design",
  extraPrice: 1,
  extraLimit: 1,
  title: "Gold",
  services: [
    "4 Days Delivery",
    "5 Revisions",
    "Number of illustrations 50 (optional)",
    "Cover Formating",
    "All trim size options",
    "3D Mockup",
    "Source File",
    "All trim size options",
    "Paperback And eBook",
    "Print Ready PDF",
    "EBook Files (EPUB, MOBI, DOCX)",
    "Help In Approving from KDP",
  ],
  price: 99,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const bookLayoutPlatinumData = {
  name: "Book Layout Design",
  extraPrice: 1,
  extraLimit: 1,
  title: "Platinum",
  services: [
    "5 Days Delivery",
    "7 Revisions",
    "Number of illustrations 50 (optional)",
    "Cover Formating",
    "All trim size options",
    "3D Mockup",
    "Source File",
    "Paperback And eBook",
    "Print Ready PDF",
    "EBook Files (EPUB, MOBI, DOCX)",
    "Help In Approving from KDP",
    "10 Days support",
  ],
  price: 149,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

// 4)Perfectly Publishing on Amazon KDP

const amazonPubishingData = {
  name: "Perfectly Publishing on Amazon KDP",
  extraPrice: 4,
  extraLimit: 1,
  title: "Publishing",
  services: [
    "7 Days Delivery",
    "3 Revisions",
    "Formatting for Amazon",
    "Number of pages 50(optional)",
    "Book Uploading",
    "1 Niche",
    "3 Categories",
    "Keyword 50 (optional)",
    "Competitive Analysis",
  ],
  price: 199,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const amazonPubishingCampaignData = {
  name: "Perfectly Publishing on Amazon KDP",
  extraPrice: 4,
  extraLimit: 1,
  title: "Publishing",
  services: [
    "20 Days Delivery",
    "5 Revisions",
    "BOOK Formatting KDP",
    "Number of pages 50(optional)",
    "Book Uploading",
    "1 Niche",
    "Cover SEO",
    "Book Uploading",
    "Competitive Analysis",
    "SEO Optimized listing Description",
    "Launch Strategy",
    "Promotional Campaign",
    "PPC setup and Optimization",
    "10 Categories",
    "Keyword 100 (optional)",
    "Competitive Analysis",
    "30 days support ",
  ],
  price: 249,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

// Video Animation

const videoSilverData = {
  name: "Video Animation",
  extraPrice: 1,
  extraLimit: 1,
  title: "Silver",
  services: [
    "Up to 60 Seconds Running Time (optional)",
    "Full Color",
    "Voice Over Recording",
    "Music/Sound Design included",
  ],
  price: 299,
  totalPrice: 0,
  extra: 0,
  options: false,
  extraType: "",
};

const videoGoldData = {
  name: "Video Animation",
  extraPrice: 1,
  extraLimit: 1,
  title: "Gold",
  services: [
    "Up to 60 Seconds Running Time (optional)",
    "Full Color",
    "Voice Over Recording",
    "Script writing",
    "Music/Sound Design included",
    "Illustrated Background included",
    "Original Design",
  ],
  price: 399,
  totalPrice: 0,
  extra: 0,
  options: false,
  extraType: "",
};

const videoPlatinumData = {
  name: "Video Animation",
  extraPrice: 1,
  extraLimit: 1,
  title: "Platinum",
  services: [
    "Up to 60 Seconds Running Time (optional)",
    "Full Color",
    "Script writing",
    "Voice Over Recording",
    "Music/Sound Design included",
    "Illustrated Background included",
    "Original Design",
    "Multiple revisions",
    "5 days support ",
  ],
  price: 649,
  totalPrice: 0,
  extra: 0,
  options: false,
  extraType: "",
};

// 6)YouTube Video Content Creation

const youtubeSilverData = {
  name: "YouTube Video Content Creation",
  extraPrice: 1,
  extraLimit: 1,
  title: "Silver",
  services: [
    "3 days",
    "5 Revisions",
    "0-5 Min video, your Script",
    "Male/ Female Human Voiceover",
    "Professional Video Content",
    "Thumbnail",
    "Keywords Research",
    "Videos on Every Niche",
    "Video SEO",
    "Background Music",
  ],
  price: 24,
  totalPrice: 0,
  extra: 0,
  options: false,
  extraType: "",
};

const youtubeGoldData = {
  name: "YouTube Video Content Creation",
  extraPrice: 1,
  extraLimit: 1,
  title: "Gold",
  services: [
    "5 days",
    "7 Revisions",
    "0-10 Min video, your Script",
    "Male/ Female Human Voiceover",
    "Professional Video Content",
    "Thumbnail",
    "Keywords Research",
    "Videos on Every Niche",
    "Video SEO",
    "Motion Graphic",
    "Background Music",
  ],
  price: 49,
  totalPrice: 0,
  extra: 0,
  options: false,
  extraType: "",
};

const youtubePlatinumData = {
  name: "YouTube Video Content Creation",
  extraPrice: 1,
  extraLimit: 1,
  title: "Platinum",
  services: [
    "8 days",
    "Unlimited Revisions",
    "0-30 Min video, your Script",
    "Male/ Female Human Voiceover",
    "Professional Video Content",
    "Thumbnail",
    "Keywords Research",
    "Videos on Every Niche",
    "Video SEO",
    "Background Music",
    "5 Days Support",
  ],
  price: 149,
  totalPrice: 0,
  extra: 0,
  options: false,
  extraType: "",
};

// Website designing
const websiteSilverData = {
  name: "Website Designing",
  extraPrice: 20,
  extraLimit: 1,
  title: "Silver",
  services: [
    "3 Days Delivery",
    "3 Revision",
    "1 Pages/Screens",
    "Pixel perfect UI Design",
    "Prototype",
    "Source File",
  ],
  price: 49,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const webisteGoldData = {
  name: "Website Designing",
  extraPrice: 20,
  extraLimit: 1,
  title: "Gold",
  services: [
    "5 Days Delivery",
    "5 Revision",
    "3 Pages/Screens",
    "1 custom asset",
    "Pixel perfect UI Design",
    "Prototype",
    "Source File",
  ],
  price: 99,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const websitePlatinumData = {
  name: "Website Designing",
  extraPrice: 20,
  extraLimit: 1,
  title: "Platinum",
  services: [
    "12 Days Delivery",
    "8 Revision",
    "8 Pages/Screens",
    "Responsive Design",
    "Content Upload",
    "Pixel perfect UI Design",
    "Prototype",
    "Source File",
  ],
  price: 149,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

// Mobile Application Design
const appSilverData = {
  name: "Mobile Application Design",
  extraPrice: 20,
  extraLimit: 1,
  title: "Silver",
  services: [
    "3 Days Delivery",
    "3 Revision",
    "5 Pages/Screens",
    "Responsive Design",
    "Wireframes",
    "Source File",
  ],
  price: 149,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const appGoldData = {
  name: "Mobile Application Design",
  extraPrice: 20,
  extraLimit: 1,
  title: "Gold",
  services: [
    "5 Days Delivery",
    "5 Revision",
    "15 Pages/Screens",
    "Responsive Design",
    "Wireframes",
    "Source File",
  ],
  price: 349,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

const appPlatinumData = {
  name: "Mobile Application Design",
  extraPrice: 20,
  extraLimit: 1,
  title: "Platinum",
  services: [
    "12 Days Delivery",
    "8 Revision",
    "25 Pages/Screens",
    "Responsive Design",
    "Wireframes",
    "Source File",
  ],
  price: 499,
  totalPrice: 0,
  extra: 0,
  options: true,
  extraType: "pages",
};

export {
  storyWritingGoldData,
  storyWritingSilverData,
  storyWritingPlatinumData,
  bookCoverGoldData,
  bookCoverPlatinumData,
  bookCoverSilverData,
  bookFullandFlaggerData,
  bookInteriorColoringData,
  bookInteriorEbookData,
  bookInteriorPaperbackgData,
  bookLayoutGoldData,
  bookLayoutPlatinumData,
  bookLayoutSilverData,
  youtubeGoldData,
  youtubePlatinumData,
  youtubeSilverData,
  amazonPubishingCampaignData,
  amazonPubishingData,
  videoGoldData,
  videoPlatinumData,
  videoSilverData,
  webisteGoldData,
  websitePlatinumData,
  websiteSilverData,
  appGoldData,
  appPlatinumData,
  appSilverData,
};
